### ISSUE TITLE
Building `wn_bin` still unable to find correct runtime

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#193] opened 2018-03-16 12:05 UTC
as discussed in the meeting, we bumped DDS version to 2.0 and turned back on `wn_bin`.

This breaks the build with:

```
-- Using BOOST Library dir: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.64.0-alice1-5/lib
-- prerequisite dirs: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.64.0-alice1-5/lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-user-defaults;/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-protocol-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-intercom-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-topology-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/MiscCommon/dds_ncf;
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-intercom-lib/libdds_intercom_lib.so'
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-protocol-lib/libdds_protocol_lib.so'
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/dds-user-defaults/libdds-user-defaults.so'
WN PKG prerequisite='/usr/lib/libgcc_s.so.1'
-- 
warning: cannot resolve item 'libstdc++.so.6'

  possible problems:
    need more directories?
    need to use InstallRequiredSystemLibraries?
    run in install tree instead of build tree?

WN PKG prerequisite='libstdc++.so.6'
CMake Error at /mnt/mesos/sandbox/sandbox/sw/SOURCES/DDS/2.0/2.0/cmake/modules/DDS_CollectPrerequisites.cmake:33 (file):
  file COPY cannot find
  "/mnt/mesos/sandbox/sandbox/sw/BUILD/802c478124d7a246131b23ed240a8efdbdbc42ca/DDS/libstdc++.so.6".
```

@MohammadAlTurany @rbx given CVMFS is available if DDS itself is picked up from CVMFS, do we really need the `wn_bin` part for our tests?

**Comment by AnarManafov** [comment] 2018-03-16 19:12
Looks to me like a duplicate of #175.
Please see the solution on the ticket.

Feel free to reopen if the problem persist even after using the solution from #175

**Closed by AnarManafov** 2018-03-16 19:12 UTC
