### ISSUE TITLE
DDS fails to build on macOS Catalina

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#270] opened 2019-10-17 10:14 UTC
I had several reports about:

```
DEBUG:O2:DDS:0: ld: symbol(s) not found for architecture x86_64
DEBUG:O2:DDS:0: clang: error: linker command failed with exit code 1 (use -v to see invocation)
DEBUG:O2:DDS:0: make[2]: *** [MiscCommon/pipe_log_engine/libpipe_log_engine.dylib] Error 1
DEBUG:O2:DDS:0: make[1]: *** [MiscCommon/pipe_log_engine/CMakeFiles/pipe_log_engine.dir/all] Error 2
DEBUG:O2:DDS:0: make: *** [all] Error 2
```

**Comment by AnarManafov** [comment] 2019-10-17 10:29
Hey @ktf ,

is it possible to get a full cmake output (with its log files)?

**Comment by AnarManafov** [comment] 2019-11-22 09:09
Unfortunately we can't reproduce this. We tried on several different machine using the current OS X.

I guess, we can close it for now. But feel free to reopen if the issue persists or you have more information.

**Closed by AnarManafov** 2019-11-22 09:09 UTC
