### ISSUE TITLE
prints on .bashrc seem to make dds-submit fail

### ISSUE THREAD

**Issue by vascobarroso** [FairRootGroup/DDS#123] opened 2016-03-24 11:47 UTC
prints on .bashrc seem to make dds-submit fail:

```

2016-03-24 12:26:34.971886   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: flp01      [Thu, 24 Mar 2016 12:26:34 +0100]       protocol version mismatc
2016-03-24 12:26:34.972221   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: h -- is your shell clean?

2016-03-24 12:26:34.974699   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: flp01      [Thu, 24 Mar 2016 12:26:34 +0100]       (see the rsync man page 
2016-03-24 12:26:34.974902   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: for an explanation)

2016-03-24 12:26:34.976971   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: flp01      [Thu, 24 Mar 2016 12:26:34 +0100]       rsync error: protocol in
2016-03-24 12:26:34.977156   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: compatibility (code 2) at compat.c(171) [sender=3.0.6]

2016-03-24 12:26:34.979532   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: flp01      [Thu, 24 Mar 2016 12:26:34 +0100]       dds-submit-ssh-worker er
2016-03-24 12:26:34.979712   inf    dds-submit-ssh       <0x0000485c:0x00007f6303fff700>    pipe log engine: ror: failed to send worker's package
```

Is there any way to overcome this (apart from removing the prints from .bashrc) ?

**Comment by AnarManafov** [comment] 2016-03-24 15:23
Vasco, can you please give more details on how we can repro. this issue?

**Comment by vascobarroso** [comment] 2016-03-24 15:42
@AnarManafov On my slc6 setup, I can reproduce it by simply adding a 
```
echo "hello"
```
to the .bashrc of the account used in the plugin configuration file.

**Comment by AnarManafov** [comment] 2016-03-24 15:43
thank you. I will look into it.

**Comment by AnarManafov** [comment] 2017-03-24 11:32
Hey Vasco,

can you please try with the latest version on the master?
I use CentOS 7 and unfortunately can't reproduce this issue :(

**Comment by AnarManafov** [comment] 2017-03-26 18:24
I am closing it for now. But please feel free to reopen if the problem persists in DDS 1.6

**Closed by AnarManafov** 2017-03-26 18:24 UTC
